### ISSUE TITLE
Add --squash when its available

### ISSUE THREAD

**Issue by agnesk92** [GameAnalytics/github#1]
https://docs.docker.com/engine/reference/commandline/image_build/
https://github.com/actions/virtual-environments/issues/3090

Add the squash option when it is not experimental anymore or GitHub actions starts support for running dockerd in experimental mode.

**Comment by ddosia** [comment]
now you can pass any arguments to the docker through [https://github.com/GameAnalytics/github/tree/v0/actions/build-push-ecr#usage](docker-build-args)
